todo:
    build: ./app
    ports:
        - 80:80
    links:
        - mysql:db
mysql:
    image: mysql:5.6
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=tasks
    volumes_from:
        - data_container
data_container:
    image: mysql:5.6
    command: "true"
    volumes:
        - /var/lib/mysql